### ISSUE TITLE
Identify all of the I18N keys that are used

### ISSUE THREAD

**Issue by jwieringa** [rubyforgood/AllIncomeFoods#14]

**Comment by kwals** [comment]
Right now, the symbols :credits1 through :or_address are being used.  

On the develop branch one view is different, so :or_address and :indexsearch2 are not being used (They were being used in the example search "Eg, 43402, San Fran" below the search bar).

The English locale file does not have any other :symbols, but the Spanish and Chinese files have quite a few extra symbols.
