### ISSUE TITLE
Data on farmer's markets accepting SNAP available through app

### ISSUE THREAD

**Issue by AimeeAllen** [rubyforgood/AllIncomeFoods#26]

**Comment by zph** [comment]
See https://hackpad.com/Project-Snapfresh.org-jNHpAeYS5rQ comments under Farmers Market heading. We have data available and scraped. But need to make scrape repeatable and memory efficient, then integrate into APP's data.

**Comment by jwieringa** [comment]
Migrated to primary repo. https://github.com/SnapFresh/SnapFresh/issues/54
